### ISSUE TITLE
请问睡眠是否正常？

### ISSUE THREAD

**Issue by Kaijun** [MagicianLjj/MSI-B450m-MORTAR-Hackintosh#2]
我自己做了一遍 EFI，发现睡眠一直有问题

USB 重新 Map 后还是不行

请教下 OP 是否已经解决了睡眠问题？能否参考下解法

**Comment by MagicianLjj** [comment]
> 我自己做了一遍 EFI，发现睡眠一直有问题
> 
> USB 重新 Map 后还是不行
> 
> 请教下 OP 是否已经解决了睡眠问题？能否参考下解法

@Kaijun 是的 与usb定制无关，需要bios关闭Resize Bar  然后修改ResizeAppleGpuBars 为-1

**Comment by Kaijun** [comment]
> 

感谢你的快速回复，我看 bios Resize Bar  默认是关闭的，ResizeAppleGpuBars 默认也是 -1

大佬能不能指导下怎么 debug 到底是什么原因造成的睡死及唤醒的问题

我现在的情况是很偶尔的情况下能进入睡眠，但是唤醒黑屏。大部分时候是直接进不去睡眠，也无法唤醒

**Comment by Kaijun** [comment]
大佬另外我看你 kext 包含了 USBInjectAll 这个应该在定制完 USB 后就要去除了

**Comment by MagicianLjj** [comment]
> > 
> 
> 感谢你的快速回复，我看 bios Resize Bar 默认是关闭的，ResizeAppleGpuBars 默认也是 -1
> 
> 大佬能不能指导下怎么 debug 到底是什么原因造成的睡死及唤醒的问题
> 
> 我现在的情况是很偶尔的情况下能进入睡眠，但是唤醒黑屏。大部分时候是直接进不去睡眠，也无法唤醒

@Kaijun 不好意思  debug这些我也不清楚 关闭Resize Bar 必须加上启动参数npci=0x3000
如果同主板可以直接试试我最新的config，另外USBInjectAll 只是放着方便，并没有启用

**Comment by Kaijun** [comment]
@MagicianLjj 感谢，我直接用你的 efi + 自己的 smbios 试一下

我是同主板，但是是 5600g (带 igfx) 以及 rx580，感觉也不排除是 igfx 的问题

我先试一下

**Comment by Kaijun** [comment]
@MagicianLjj 老哥不好意思再确认下，我看你的 WhateverGreen 也是禁用的，这个是符合预期的吗？

是因为什么原因禁用的

**Comment by MagicianLjj** [comment]
@Kaijun 6600xt  不太依赖 WhateverGreen  不需要额外驱动  rx580你可以启用

**Comment by Kaijun** [comment]
@MagicianLjj 完全用你的 OC 还是不太行，进不去深度睡眠，我再看看啥问题谢谢

**Comment by Kaijun** [comment]
@MagicianLjj 在 BIOS 里关掉 IOMMU 后看起来能进睡眠了！这个感觉也是个很关键的选项

**Comment by Kaijun** [comment]
最终发现应该是 5600g 自带核显导致的睡眠不了

加上 -wegnoigpu 屏蔽 IGPU 就解决了

感谢！
